services:
  hurtigruten:
    image: hurtigruten
    build:
      context: hurtigruten
      dockerfile: hurtigruten/src/main/docker/Dockerfile.jvm
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/hurtigruten
      - QUARKUS_DATASOURCE_USERNAME=root
      - QUARKUS_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"
    depends_on:
      - postgres
#    networks:
#      - hurtigruten-network

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=hurtigruten
#    networks:
#      - hurtigruten-network
#
#networks:
#  hurtigruten-network:
#    name: hurtigruten-network
