services:

  hurtigruten:
    container_name: hurtigruten
    build:
      context: hurtigruten
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      QUARKUS_HTTP_CORS_ORIGINS: http://localhost:4200 # edit this is you change the web-view port
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  geo-data-producer:
    container_name: geo-data-producer
    env_file:
      - geo-data-producer/.env
    build:
      context: geo-data-producer
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    ports:
      - "8081:8080"
    depends_on:
      - kafka
        
  ais-stream-processor:
    container_name: ais-stream-processor
    build:
      context:  ais-stream-processor
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      QUARKUS_HTTP_CORS_ORIGINS: http://localhost:4200 # edit this is you change the web-view port
    ports:
      - "8082:8080"
    depends_on:
      - kafka

  web-view:
    container_name: web-view
    build:
      context: web-view
    ports:
      - "4200:80"
    environment:
      # since we are making the requests from the browser, using localhost with the exposed port of the services works
      AIS_STREAM_URI: http://localhost:8080
      AIS_AGGREGATION_URI: http://localhost:8082
    depends_on:
      - hurtigruten

  kafka:
    image: apache/kafka:3.7.2
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Configure listeners for both docker and host communication
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      # Listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - '8888:8080'
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
      LOGGING_LEVEL_ORG_APACHE_KAFKA_CLIENTS_ADMIN: "ERROR"
    depends_on:
      - kafka