services:

  hurtigruten:
    container_name: hurtigruten
    build:
      context: hurtigruten
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/hurtigruten
      QUARKUS_DATASOURCE_USERNAME: root
      QUARKUS_DATASOURCE_PASSWORD: root
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      # QUARKUS_HTTP_CORS_ORIGINS: http://localhost:4200 # edit this is you change the frontend port
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
      - geo-data-producer

  geo-data-producer:
    container_name: geo-data-producer
    build:
      context: geo-data-producer
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    ports:
      - "8081:8080"
    depends_on:
      - kafka
        
  ais-stream-processor:
    container_name: ais-stream-processor
    build:
      context:  ais-stream-processor
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    ports:
      - "8082:8080"
    depends_on:
      - kafka
      - geo-data-producer
      - hurtigruten

  # TODO: add angular frontend
  web-view:
    container_name: web-view
    build:
      context: web-view
    ports:
      - "4200:80"  # Expose Angular via Nginx on port 4200
    environment:
      AIS_STREAM_URI: http://hurtigruten:8080  # set url to hurtigruten service
    depends_on:
      - hurtigruten

  postgres:
    image: postgres:17.3-bookworm
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: hurtigruten

  kafka:
    image: apache/kafka:3.7.2
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Configure listeners for both docker and host communication
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      # Listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - '8888:8080'
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka