/*
 * Ais-Stream WebsocketObjects
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AisMessageTypes;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SubscriptionMessage
 */
public class SubscriptionMessageTest {
    private final SubscriptionMessage model = new SubscriptionMessage();

    /**
     * Model tests for SubscriptionMessage
     */
    @Test
    public void testSubscriptionMessage() {
        // TODO: test SubscriptionMessage
    }

    /**
     * Test the property 'apIKey'
     */
    @Test
    public void apIKeyTest() {
        // TODO: test apIKey
    }

    /**
     * Test the property 'boundingBoxes'
     */
    @Test
    public void boundingBoxesTest() {
        // TODO: test boundingBoxes
    }

    /**
     * Test the property 'filtersShipMMSI'
     */
    @Test
    public void filtersShipMMSITest() {
        // TODO: test filtersShipMMSI
    }

    /**
     * Test the property 'filterMessageTypes'
     */
    @Test
    public void filterMessageTypesTest() {
        // TODO: test filterMessageTypes
    }

}
