/*
 * Ais-Stream WebsocketObjects
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * AddressedBinaryMessageApplicationID
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-21T15:33:26.956655+01:00[Europe/Berlin]", comments = "Generator version: 7.11.0")
public class AddressedBinaryMessageApplicationID {
  public static final String SERIALIZED_NAME_VALID = "Valid";
  @SerializedName(SERIALIZED_NAME_VALID)
  @javax.annotation.Nonnull
  private Boolean valid;

  public static final String SERIALIZED_NAME_DESIGNATED_AREA_CODE = "DesignatedAreaCode";
  @SerializedName(SERIALIZED_NAME_DESIGNATED_AREA_CODE)
  @javax.annotation.Nonnull
  private Integer designatedAreaCode;

  public static final String SERIALIZED_NAME_FUNCTION_IDENTIFIER = "FunctionIdentifier";
  @SerializedName(SERIALIZED_NAME_FUNCTION_IDENTIFIER)
  @javax.annotation.Nonnull
  private Integer functionIdentifier;

  public AddressedBinaryMessageApplicationID() {
  }

  public AddressedBinaryMessageApplicationID valid(@javax.annotation.Nonnull Boolean valid) {
    this.valid = valid;
    return this;
  }

  /**
   * Get valid
   * @return valid
   */
  @javax.annotation.Nonnull
  public Boolean getValid() {
    return valid;
  }

  public void setValid(@javax.annotation.Nonnull Boolean valid) {
    this.valid = valid;
  }


  public AddressedBinaryMessageApplicationID designatedAreaCode(@javax.annotation.Nonnull Integer designatedAreaCode) {
    this.designatedAreaCode = designatedAreaCode;
    return this;
  }

  /**
   * Get designatedAreaCode
   * @return designatedAreaCode
   */
  @javax.annotation.Nonnull
  public Integer getDesignatedAreaCode() {
    return designatedAreaCode;
  }

  public void setDesignatedAreaCode(@javax.annotation.Nonnull Integer designatedAreaCode) {
    this.designatedAreaCode = designatedAreaCode;
  }


  public AddressedBinaryMessageApplicationID functionIdentifier(@javax.annotation.Nonnull Integer functionIdentifier) {
    this.functionIdentifier = functionIdentifier;
    return this;
  }

  /**
   * Get functionIdentifier
   * @return functionIdentifier
   */
  @javax.annotation.Nonnull
  public Integer getFunctionIdentifier() {
    return functionIdentifier;
  }

  public void setFunctionIdentifier(@javax.annotation.Nonnull Integer functionIdentifier) {
    this.functionIdentifier = functionIdentifier;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressedBinaryMessageApplicationID addressedBinaryMessageApplicationID = (AddressedBinaryMessageApplicationID) o;
    return Objects.equals(this.valid, addressedBinaryMessageApplicationID.valid) &&
        Objects.equals(this.designatedAreaCode, addressedBinaryMessageApplicationID.designatedAreaCode) &&
        Objects.equals(this.functionIdentifier, addressedBinaryMessageApplicationID.functionIdentifier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(valid, designatedAreaCode, functionIdentifier);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressedBinaryMessageApplicationID {\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("    designatedAreaCode: ").append(toIndentedString(designatedAreaCode)).append("\n");
    sb.append("    functionIdentifier: ").append(toIndentedString(functionIdentifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Valid");
    openapiFields.add("DesignatedAreaCode");
    openapiFields.add("FunctionIdentifier");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("Valid");
    openapiRequiredFields.add("DesignatedAreaCode");
    openapiRequiredFields.add("FunctionIdentifier");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AddressedBinaryMessageApplicationID
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AddressedBinaryMessageApplicationID.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AddressedBinaryMessageApplicationID is not found in the empty JSON string", AddressedBinaryMessageApplicationID.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AddressedBinaryMessageApplicationID.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AddressedBinaryMessageApplicationID` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AddressedBinaryMessageApplicationID.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AddressedBinaryMessageApplicationID.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AddressedBinaryMessageApplicationID' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AddressedBinaryMessageApplicationID> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AddressedBinaryMessageApplicationID.class));

       return (TypeAdapter<T>) new TypeAdapter<AddressedBinaryMessageApplicationID>() {
           @Override
           public void write(JsonWriter out, AddressedBinaryMessageApplicationID value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AddressedBinaryMessageApplicationID read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AddressedBinaryMessageApplicationID given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AddressedBinaryMessageApplicationID
   * @throws IOException if the JSON string is invalid with respect to AddressedBinaryMessageApplicationID
   */
  public static AddressedBinaryMessageApplicationID fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AddressedBinaryMessageApplicationID.class);
  }

  /**
   * Convert an instance of AddressedBinaryMessageApplicationID to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

