/*
 * Ais-Stream WebsocketObjects
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * BaseStationReport
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-21T15:33:26.956655+01:00[Europe/Berlin]", comments = "Generator version: 7.11.0")
public class BaseStationReport {
  public static final String SERIALIZED_NAME_MESSAGE_I_D = "MessageID";
  @SerializedName(SERIALIZED_NAME_MESSAGE_I_D)
  @javax.annotation.Nonnull
  private Integer messageID;

  public static final String SERIALIZED_NAME_REPEAT_INDICATOR = "RepeatIndicator";
  @SerializedName(SERIALIZED_NAME_REPEAT_INDICATOR)
  @javax.annotation.Nonnull
  private Integer repeatIndicator;

  public static final String SERIALIZED_NAME_USER_I_D = "UserID";
  @SerializedName(SERIALIZED_NAME_USER_I_D)
  @javax.annotation.Nonnull
  private Integer userID;

  public static final String SERIALIZED_NAME_VALID = "Valid";
  @SerializedName(SERIALIZED_NAME_VALID)
  @javax.annotation.Nonnull
  private Boolean valid;

  public static final String SERIALIZED_NAME_UTC_YEAR = "UtcYear";
  @SerializedName(SERIALIZED_NAME_UTC_YEAR)
  @javax.annotation.Nonnull
  private Integer utcYear;

  public static final String SERIALIZED_NAME_UTC_MONTH = "UtcMonth";
  @SerializedName(SERIALIZED_NAME_UTC_MONTH)
  @javax.annotation.Nonnull
  private Integer utcMonth;

  public static final String SERIALIZED_NAME_UTC_DAY = "UtcDay";
  @SerializedName(SERIALIZED_NAME_UTC_DAY)
  @javax.annotation.Nonnull
  private Integer utcDay;

  public static final String SERIALIZED_NAME_UTC_HOUR = "UtcHour";
  @SerializedName(SERIALIZED_NAME_UTC_HOUR)
  @javax.annotation.Nonnull
  private Integer utcHour;

  public static final String SERIALIZED_NAME_UTC_MINUTE = "UtcMinute";
  @SerializedName(SERIALIZED_NAME_UTC_MINUTE)
  @javax.annotation.Nonnull
  private Integer utcMinute;

  public static final String SERIALIZED_NAME_UTC_SECOND = "UtcSecond";
  @SerializedName(SERIALIZED_NAME_UTC_SECOND)
  @javax.annotation.Nonnull
  private Integer utcSecond;

  public static final String SERIALIZED_NAME_POSITION_ACCURACY = "PositionAccuracy";
  @SerializedName(SERIALIZED_NAME_POSITION_ACCURACY)
  @javax.annotation.Nonnull
  private Boolean positionAccuracy;

  public static final String SERIALIZED_NAME_LONGITUDE = "Longitude";
  @SerializedName(SERIALIZED_NAME_LONGITUDE)
  @javax.annotation.Nonnull
  private Double longitude;

  public static final String SERIALIZED_NAME_LATITUDE = "Latitude";
  @SerializedName(SERIALIZED_NAME_LATITUDE)
  @javax.annotation.Nonnull
  private Double latitude;

  public static final String SERIALIZED_NAME_FIX_TYPE = "FixType";
  @SerializedName(SERIALIZED_NAME_FIX_TYPE)
  @javax.annotation.Nonnull
  private Integer fixType;

  public static final String SERIALIZED_NAME_LONG_RANGE_ENABLE = "LongRangeEnable";
  @SerializedName(SERIALIZED_NAME_LONG_RANGE_ENABLE)
  @javax.annotation.Nonnull
  private Boolean longRangeEnable;

  public static final String SERIALIZED_NAME_SPARE = "Spare";
  @SerializedName(SERIALIZED_NAME_SPARE)
  @javax.annotation.Nonnull
  private Integer spare;

  public static final String SERIALIZED_NAME_RAIM = "Raim";
  @SerializedName(SERIALIZED_NAME_RAIM)
  @javax.annotation.Nonnull
  private Boolean raim;

  public static final String SERIALIZED_NAME_COMMUNICATION_STATE = "CommunicationState";
  @SerializedName(SERIALIZED_NAME_COMMUNICATION_STATE)
  @javax.annotation.Nonnull
  private Integer communicationState;

  public BaseStationReport() {
  }

  public BaseStationReport messageID(@javax.annotation.Nonnull Integer messageID) {
    this.messageID = messageID;
    return this;
  }

  /**
   * Get messageID
   * @return messageID
   */
  @javax.annotation.Nonnull
  public Integer getMessageID() {
    return messageID;
  }

  public void setMessageID(@javax.annotation.Nonnull Integer messageID) {
    this.messageID = messageID;
  }


  public BaseStationReport repeatIndicator(@javax.annotation.Nonnull Integer repeatIndicator) {
    this.repeatIndicator = repeatIndicator;
    return this;
  }

  /**
   * Get repeatIndicator
   * @return repeatIndicator
   */
  @javax.annotation.Nonnull
  public Integer getRepeatIndicator() {
    return repeatIndicator;
  }

  public void setRepeatIndicator(@javax.annotation.Nonnull Integer repeatIndicator) {
    this.repeatIndicator = repeatIndicator;
  }


  public BaseStationReport userID(@javax.annotation.Nonnull Integer userID) {
    this.userID = userID;
    return this;
  }

  /**
   * Get userID
   * @return userID
   */
  @javax.annotation.Nonnull
  public Integer getUserID() {
    return userID;
  }

  public void setUserID(@javax.annotation.Nonnull Integer userID) {
    this.userID = userID;
  }


  public BaseStationReport valid(@javax.annotation.Nonnull Boolean valid) {
    this.valid = valid;
    return this;
  }

  /**
   * Get valid
   * @return valid
   */
  @javax.annotation.Nonnull
  public Boolean getValid() {
    return valid;
  }

  public void setValid(@javax.annotation.Nonnull Boolean valid) {
    this.valid = valid;
  }


  public BaseStationReport utcYear(@javax.annotation.Nonnull Integer utcYear) {
    this.utcYear = utcYear;
    return this;
  }

  /**
   * Get utcYear
   * @return utcYear
   */
  @javax.annotation.Nonnull
  public Integer getUtcYear() {
    return utcYear;
  }

  public void setUtcYear(@javax.annotation.Nonnull Integer utcYear) {
    this.utcYear = utcYear;
  }


  public BaseStationReport utcMonth(@javax.annotation.Nonnull Integer utcMonth) {
    this.utcMonth = utcMonth;
    return this;
  }

  /**
   * Get utcMonth
   * @return utcMonth
   */
  @javax.annotation.Nonnull
  public Integer getUtcMonth() {
    return utcMonth;
  }

  public void setUtcMonth(@javax.annotation.Nonnull Integer utcMonth) {
    this.utcMonth = utcMonth;
  }


  public BaseStationReport utcDay(@javax.annotation.Nonnull Integer utcDay) {
    this.utcDay = utcDay;
    return this;
  }

  /**
   * Get utcDay
   * @return utcDay
   */
  @javax.annotation.Nonnull
  public Integer getUtcDay() {
    return utcDay;
  }

  public void setUtcDay(@javax.annotation.Nonnull Integer utcDay) {
    this.utcDay = utcDay;
  }


  public BaseStationReport utcHour(@javax.annotation.Nonnull Integer utcHour) {
    this.utcHour = utcHour;
    return this;
  }

  /**
   * Get utcHour
   * @return utcHour
   */
  @javax.annotation.Nonnull
  public Integer getUtcHour() {
    return utcHour;
  }

  public void setUtcHour(@javax.annotation.Nonnull Integer utcHour) {
    this.utcHour = utcHour;
  }


  public BaseStationReport utcMinute(@javax.annotation.Nonnull Integer utcMinute) {
    this.utcMinute = utcMinute;
    return this;
  }

  /**
   * Get utcMinute
   * @return utcMinute
   */
  @javax.annotation.Nonnull
  public Integer getUtcMinute() {
    return utcMinute;
  }

  public void setUtcMinute(@javax.annotation.Nonnull Integer utcMinute) {
    this.utcMinute = utcMinute;
  }


  public BaseStationReport utcSecond(@javax.annotation.Nonnull Integer utcSecond) {
    this.utcSecond = utcSecond;
    return this;
  }

  /**
   * Get utcSecond
   * @return utcSecond
   */
  @javax.annotation.Nonnull
  public Integer getUtcSecond() {
    return utcSecond;
  }

  public void setUtcSecond(@javax.annotation.Nonnull Integer utcSecond) {
    this.utcSecond = utcSecond;
  }


  public BaseStationReport positionAccuracy(@javax.annotation.Nonnull Boolean positionAccuracy) {
    this.positionAccuracy = positionAccuracy;
    return this;
  }

  /**
   * Get positionAccuracy
   * @return positionAccuracy
   */
  @javax.annotation.Nonnull
  public Boolean getPositionAccuracy() {
    return positionAccuracy;
  }

  public void setPositionAccuracy(@javax.annotation.Nonnull Boolean positionAccuracy) {
    this.positionAccuracy = positionAccuracy;
  }


  public BaseStationReport longitude(@javax.annotation.Nonnull Double longitude) {
    this.longitude = longitude;
    return this;
  }

  /**
   * Get longitude
   * @return longitude
   */
  @javax.annotation.Nonnull
  public Double getLongitude() {
    return longitude;
  }

  public void setLongitude(@javax.annotation.Nonnull Double longitude) {
    this.longitude = longitude;
  }


  public BaseStationReport latitude(@javax.annotation.Nonnull Double latitude) {
    this.latitude = latitude;
    return this;
  }

  /**
   * Get latitude
   * @return latitude
   */
  @javax.annotation.Nonnull
  public Double getLatitude() {
    return latitude;
  }

  public void setLatitude(@javax.annotation.Nonnull Double latitude) {
    this.latitude = latitude;
  }


  public BaseStationReport fixType(@javax.annotation.Nonnull Integer fixType) {
    this.fixType = fixType;
    return this;
  }

  /**
   * Get fixType
   * @return fixType
   */
  @javax.annotation.Nonnull
  public Integer getFixType() {
    return fixType;
  }

  public void setFixType(@javax.annotation.Nonnull Integer fixType) {
    this.fixType = fixType;
  }


  public BaseStationReport longRangeEnable(@javax.annotation.Nonnull Boolean longRangeEnable) {
    this.longRangeEnable = longRangeEnable;
    return this;
  }

  /**
   * Get longRangeEnable
   * @return longRangeEnable
   */
  @javax.annotation.Nonnull
  public Boolean getLongRangeEnable() {
    return longRangeEnable;
  }

  public void setLongRangeEnable(@javax.annotation.Nonnull Boolean longRangeEnable) {
    this.longRangeEnable = longRangeEnable;
  }


  public BaseStationReport spare(@javax.annotation.Nonnull Integer spare) {
    this.spare = spare;
    return this;
  }

  /**
   * Get spare
   * @return spare
   */
  @javax.annotation.Nonnull
  public Integer getSpare() {
    return spare;
  }

  public void setSpare(@javax.annotation.Nonnull Integer spare) {
    this.spare = spare;
  }


  public BaseStationReport raim(@javax.annotation.Nonnull Boolean raim) {
    this.raim = raim;
    return this;
  }

  /**
   * Get raim
   * @return raim
   */
  @javax.annotation.Nonnull
  public Boolean getRaim() {
    return raim;
  }

  public void setRaim(@javax.annotation.Nonnull Boolean raim) {
    this.raim = raim;
  }


  public BaseStationReport communicationState(@javax.annotation.Nonnull Integer communicationState) {
    this.communicationState = communicationState;
    return this;
  }

  /**
   * Get communicationState
   * @return communicationState
   */
  @javax.annotation.Nonnull
  public Integer getCommunicationState() {
    return communicationState;
  }

  public void setCommunicationState(@javax.annotation.Nonnull Integer communicationState) {
    this.communicationState = communicationState;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BaseStationReport baseStationReport = (BaseStationReport) o;
    return Objects.equals(this.messageID, baseStationReport.messageID) &&
        Objects.equals(this.repeatIndicator, baseStationReport.repeatIndicator) &&
        Objects.equals(this.userID, baseStationReport.userID) &&
        Objects.equals(this.valid, baseStationReport.valid) &&
        Objects.equals(this.utcYear, baseStationReport.utcYear) &&
        Objects.equals(this.utcMonth, baseStationReport.utcMonth) &&
        Objects.equals(this.utcDay, baseStationReport.utcDay) &&
        Objects.equals(this.utcHour, baseStationReport.utcHour) &&
        Objects.equals(this.utcMinute, baseStationReport.utcMinute) &&
        Objects.equals(this.utcSecond, baseStationReport.utcSecond) &&
        Objects.equals(this.positionAccuracy, baseStationReport.positionAccuracy) &&
        Objects.equals(this.longitude, baseStationReport.longitude) &&
        Objects.equals(this.latitude, baseStationReport.latitude) &&
        Objects.equals(this.fixType, baseStationReport.fixType) &&
        Objects.equals(this.longRangeEnable, baseStationReport.longRangeEnable) &&
        Objects.equals(this.spare, baseStationReport.spare) &&
        Objects.equals(this.raim, baseStationReport.raim) &&
        Objects.equals(this.communicationState, baseStationReport.communicationState);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageID, repeatIndicator, userID, valid, utcYear, utcMonth, utcDay, utcHour, utcMinute, utcSecond, positionAccuracy, longitude, latitude, fixType, longRangeEnable, spare, raim, communicationState);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BaseStationReport {\n");
    sb.append("    messageID: ").append(toIndentedString(messageID)).append("\n");
    sb.append("    repeatIndicator: ").append(toIndentedString(repeatIndicator)).append("\n");
    sb.append("    userID: ").append(toIndentedString(userID)).append("\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("    utcYear: ").append(toIndentedString(utcYear)).append("\n");
    sb.append("    utcMonth: ").append(toIndentedString(utcMonth)).append("\n");
    sb.append("    utcDay: ").append(toIndentedString(utcDay)).append("\n");
    sb.append("    utcHour: ").append(toIndentedString(utcHour)).append("\n");
    sb.append("    utcMinute: ").append(toIndentedString(utcMinute)).append("\n");
    sb.append("    utcSecond: ").append(toIndentedString(utcSecond)).append("\n");
    sb.append("    positionAccuracy: ").append(toIndentedString(positionAccuracy)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    fixType: ").append(toIndentedString(fixType)).append("\n");
    sb.append("    longRangeEnable: ").append(toIndentedString(longRangeEnable)).append("\n");
    sb.append("    spare: ").append(toIndentedString(spare)).append("\n");
    sb.append("    raim: ").append(toIndentedString(raim)).append("\n");
    sb.append("    communicationState: ").append(toIndentedString(communicationState)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("MessageID");
    openapiFields.add("RepeatIndicator");
    openapiFields.add("UserID");
    openapiFields.add("Valid");
    openapiFields.add("UtcYear");
    openapiFields.add("UtcMonth");
    openapiFields.add("UtcDay");
    openapiFields.add("UtcHour");
    openapiFields.add("UtcMinute");
    openapiFields.add("UtcSecond");
    openapiFields.add("PositionAccuracy");
    openapiFields.add("Longitude");
    openapiFields.add("Latitude");
    openapiFields.add("FixType");
    openapiFields.add("LongRangeEnable");
    openapiFields.add("Spare");
    openapiFields.add("Raim");
    openapiFields.add("CommunicationState");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("MessageID");
    openapiRequiredFields.add("RepeatIndicator");
    openapiRequiredFields.add("UserID");
    openapiRequiredFields.add("Valid");
    openapiRequiredFields.add("UtcYear");
    openapiRequiredFields.add("UtcMonth");
    openapiRequiredFields.add("UtcDay");
    openapiRequiredFields.add("UtcHour");
    openapiRequiredFields.add("UtcMinute");
    openapiRequiredFields.add("UtcSecond");
    openapiRequiredFields.add("PositionAccuracy");
    openapiRequiredFields.add("Longitude");
    openapiRequiredFields.add("Latitude");
    openapiRequiredFields.add("FixType");
    openapiRequiredFields.add("LongRangeEnable");
    openapiRequiredFields.add("Spare");
    openapiRequiredFields.add("Raim");
    openapiRequiredFields.add("CommunicationState");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BaseStationReport
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BaseStationReport.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BaseStationReport is not found in the empty JSON string", BaseStationReport.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BaseStationReport.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BaseStationReport` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BaseStationReport.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BaseStationReport.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BaseStationReport' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BaseStationReport> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BaseStationReport.class));

       return (TypeAdapter<T>) new TypeAdapter<BaseStationReport>() {
           @Override
           public void write(JsonWriter out, BaseStationReport value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BaseStationReport read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BaseStationReport given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BaseStationReport
   * @throws IOException if the JSON string is invalid with respect to BaseStationReport
   */
  public static BaseStationReport fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BaseStationReport.class);
  }

  /**
   * Convert an instance of BaseStationReport to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

