/*
 * Ais-Stream WebsocketObjects
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * BinaryAcknowledgeDestinations0
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-21T15:33:26.956655+01:00[Europe/Berlin]", comments = "Generator version: 7.11.0")
public class BinaryAcknowledgeDestinations0 {
  public static final String SERIALIZED_NAME_VALID = "Valid";
  @SerializedName(SERIALIZED_NAME_VALID)
  @javax.annotation.Nonnull
  private Boolean valid;

  public static final String SERIALIZED_NAME_DESTINATION_I_D = "DestinationID";
  @SerializedName(SERIALIZED_NAME_DESTINATION_I_D)
  @javax.annotation.Nonnull
  private Integer destinationID;

  public static final String SERIALIZED_NAME_SEQUENCEINTEGER = "Sequenceinteger";
  @SerializedName(SERIALIZED_NAME_SEQUENCEINTEGER)
  @javax.annotation.Nonnull
  private Integer sequenceinteger;

  public BinaryAcknowledgeDestinations0() {
  }

  public BinaryAcknowledgeDestinations0 valid(@javax.annotation.Nonnull Boolean valid) {
    this.valid = valid;
    return this;
  }

  /**
   * Get valid
   * @return valid
   */
  @javax.annotation.Nonnull
  public Boolean getValid() {
    return valid;
  }

  public void setValid(@javax.annotation.Nonnull Boolean valid) {
    this.valid = valid;
  }


  public BinaryAcknowledgeDestinations0 destinationID(@javax.annotation.Nonnull Integer destinationID) {
    this.destinationID = destinationID;
    return this;
  }

  /**
   * Get destinationID
   * @return destinationID
   */
  @javax.annotation.Nonnull
  public Integer getDestinationID() {
    return destinationID;
  }

  public void setDestinationID(@javax.annotation.Nonnull Integer destinationID) {
    this.destinationID = destinationID;
  }


  public BinaryAcknowledgeDestinations0 sequenceinteger(@javax.annotation.Nonnull Integer sequenceinteger) {
    this.sequenceinteger = sequenceinteger;
    return this;
  }

  /**
   * Get sequenceinteger
   * @return sequenceinteger
   */
  @javax.annotation.Nonnull
  public Integer getSequenceinteger() {
    return sequenceinteger;
  }

  public void setSequenceinteger(@javax.annotation.Nonnull Integer sequenceinteger) {
    this.sequenceinteger = sequenceinteger;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BinaryAcknowledgeDestinations0 binaryAcknowledgeDestinations0 = (BinaryAcknowledgeDestinations0) o;
    return Objects.equals(this.valid, binaryAcknowledgeDestinations0.valid) &&
        Objects.equals(this.destinationID, binaryAcknowledgeDestinations0.destinationID) &&
        Objects.equals(this.sequenceinteger, binaryAcknowledgeDestinations0.sequenceinteger);
  }

  @Override
  public int hashCode() {
    return Objects.hash(valid, destinationID, sequenceinteger);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BinaryAcknowledgeDestinations0 {\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("    destinationID: ").append(toIndentedString(destinationID)).append("\n");
    sb.append("    sequenceinteger: ").append(toIndentedString(sequenceinteger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Valid");
    openapiFields.add("DestinationID");
    openapiFields.add("Sequenceinteger");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("Valid");
    openapiRequiredFields.add("DestinationID");
    openapiRequiredFields.add("Sequenceinteger");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BinaryAcknowledgeDestinations0
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BinaryAcknowledgeDestinations0.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BinaryAcknowledgeDestinations0 is not found in the empty JSON string", BinaryAcknowledgeDestinations0.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BinaryAcknowledgeDestinations0.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BinaryAcknowledgeDestinations0` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BinaryAcknowledgeDestinations0.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BinaryAcknowledgeDestinations0.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BinaryAcknowledgeDestinations0' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BinaryAcknowledgeDestinations0> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BinaryAcknowledgeDestinations0.class));

       return (TypeAdapter<T>) new TypeAdapter<BinaryAcknowledgeDestinations0>() {
           @Override
           public void write(JsonWriter out, BinaryAcknowledgeDestinations0 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BinaryAcknowledgeDestinations0 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BinaryAcknowledgeDestinations0 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BinaryAcknowledgeDestinations0
   * @throws IOException if the JSON string is invalid with respect to BinaryAcknowledgeDestinations0
   */
  public static BinaryAcknowledgeDestinations0 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BinaryAcknowledgeDestinations0.class);
  }

  /**
   * Convert an instance of BinaryAcknowledgeDestinations0 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

