/*
 * Ais-Stream WebsocketObjects
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ChannelManagementUnicast
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-21T15:33:26.956655+01:00[Europe/Berlin]", comments = "Generator version: 7.11.0")
public class ChannelManagementUnicast {
  public static final String SERIALIZED_NAME_ADDRESS_STATION1 = "AddressStation1";
  @SerializedName(SERIALIZED_NAME_ADDRESS_STATION1)
  @javax.annotation.Nonnull
  private Integer addressStation1;

  public static final String SERIALIZED_NAME_SPARE2 = "Spare2";
  @SerializedName(SERIALIZED_NAME_SPARE2)
  @javax.annotation.Nonnull
  private Integer spare2;

  public static final String SERIALIZED_NAME_ADDRESS_STATION2 = "AddressStation2";
  @SerializedName(SERIALIZED_NAME_ADDRESS_STATION2)
  @javax.annotation.Nonnull
  private Integer addressStation2;

  public static final String SERIALIZED_NAME_SPARE3 = "Spare3";
  @SerializedName(SERIALIZED_NAME_SPARE3)
  @javax.annotation.Nonnull
  private Integer spare3;

  public ChannelManagementUnicast() {
  }

  public ChannelManagementUnicast addressStation1(@javax.annotation.Nonnull Integer addressStation1) {
    this.addressStation1 = addressStation1;
    return this;
  }

  /**
   * Get addressStation1
   * @return addressStation1
   */
  @javax.annotation.Nonnull
  public Integer getAddressStation1() {
    return addressStation1;
  }

  public void setAddressStation1(@javax.annotation.Nonnull Integer addressStation1) {
    this.addressStation1 = addressStation1;
  }


  public ChannelManagementUnicast spare2(@javax.annotation.Nonnull Integer spare2) {
    this.spare2 = spare2;
    return this;
  }

  /**
   * Get spare2
   * @return spare2
   */
  @javax.annotation.Nonnull
  public Integer getSpare2() {
    return spare2;
  }

  public void setSpare2(@javax.annotation.Nonnull Integer spare2) {
    this.spare2 = spare2;
  }


  public ChannelManagementUnicast addressStation2(@javax.annotation.Nonnull Integer addressStation2) {
    this.addressStation2 = addressStation2;
    return this;
  }

  /**
   * Get addressStation2
   * @return addressStation2
   */
  @javax.annotation.Nonnull
  public Integer getAddressStation2() {
    return addressStation2;
  }

  public void setAddressStation2(@javax.annotation.Nonnull Integer addressStation2) {
    this.addressStation2 = addressStation2;
  }


  public ChannelManagementUnicast spare3(@javax.annotation.Nonnull Integer spare3) {
    this.spare3 = spare3;
    return this;
  }

  /**
   * Get spare3
   * @return spare3
   */
  @javax.annotation.Nonnull
  public Integer getSpare3() {
    return spare3;
  }

  public void setSpare3(@javax.annotation.Nonnull Integer spare3) {
    this.spare3 = spare3;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelManagementUnicast channelManagementUnicast = (ChannelManagementUnicast) o;
    return Objects.equals(this.addressStation1, channelManagementUnicast.addressStation1) &&
        Objects.equals(this.spare2, channelManagementUnicast.spare2) &&
        Objects.equals(this.addressStation2, channelManagementUnicast.addressStation2) &&
        Objects.equals(this.spare3, channelManagementUnicast.spare3);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressStation1, spare2, addressStation2, spare3);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelManagementUnicast {\n");
    sb.append("    addressStation1: ").append(toIndentedString(addressStation1)).append("\n");
    sb.append("    spare2: ").append(toIndentedString(spare2)).append("\n");
    sb.append("    addressStation2: ").append(toIndentedString(addressStation2)).append("\n");
    sb.append("    spare3: ").append(toIndentedString(spare3)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("AddressStation1");
    openapiFields.add("Spare2");
    openapiFields.add("AddressStation2");
    openapiFields.add("Spare3");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("AddressStation1");
    openapiRequiredFields.add("Spare2");
    openapiRequiredFields.add("AddressStation2");
    openapiRequiredFields.add("Spare3");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ChannelManagementUnicast
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ChannelManagementUnicast.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ChannelManagementUnicast is not found in the empty JSON string", ChannelManagementUnicast.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ChannelManagementUnicast.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ChannelManagementUnicast` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ChannelManagementUnicast.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ChannelManagementUnicast.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ChannelManagementUnicast' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ChannelManagementUnicast> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ChannelManagementUnicast.class));

       return (TypeAdapter<T>) new TypeAdapter<ChannelManagementUnicast>() {
           @Override
           public void write(JsonWriter out, ChannelManagementUnicast value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ChannelManagementUnicast read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ChannelManagementUnicast given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ChannelManagementUnicast
   * @throws IOException if the JSON string is invalid with respect to ChannelManagementUnicast
   */
  public static ChannelManagementUnicast fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ChannelManagementUnicast.class);
  }

  /**
   * Convert an instance of ChannelManagementUnicast to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

