/*
 * Ais-Stream WebsocketObjects
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * InterrogationStation1Msg1
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-21T15:33:26.956655+01:00[Europe/Berlin]", comments = "Generator version: 7.11.0")
public class InterrogationStation1Msg1 {
  public static final String SERIALIZED_NAME_VALID = "Valid";
  @SerializedName(SERIALIZED_NAME_VALID)
  @javax.annotation.Nonnull
  private Boolean valid;

  public static final String SERIALIZED_NAME_STATION_I_D = "StationID";
  @SerializedName(SERIALIZED_NAME_STATION_I_D)
  @javax.annotation.Nonnull
  private Integer stationID;

  public static final String SERIALIZED_NAME_MESSAGE_I_D = "MessageID";
  @SerializedName(SERIALIZED_NAME_MESSAGE_I_D)
  @javax.annotation.Nonnull
  private Integer messageID;

  public static final String SERIALIZED_NAME_SLOT_OFFSET = "SlotOffset";
  @SerializedName(SERIALIZED_NAME_SLOT_OFFSET)
  @javax.annotation.Nonnull
  private Integer slotOffset;

  public InterrogationStation1Msg1() {
  }

  public InterrogationStation1Msg1 valid(@javax.annotation.Nonnull Boolean valid) {
    this.valid = valid;
    return this;
  }

  /**
   * Get valid
   * @return valid
   */
  @javax.annotation.Nonnull
  public Boolean getValid() {
    return valid;
  }

  public void setValid(@javax.annotation.Nonnull Boolean valid) {
    this.valid = valid;
  }


  public InterrogationStation1Msg1 stationID(@javax.annotation.Nonnull Integer stationID) {
    this.stationID = stationID;
    return this;
  }

  /**
   * Get stationID
   * @return stationID
   */
  @javax.annotation.Nonnull
  public Integer getStationID() {
    return stationID;
  }

  public void setStationID(@javax.annotation.Nonnull Integer stationID) {
    this.stationID = stationID;
  }


  public InterrogationStation1Msg1 messageID(@javax.annotation.Nonnull Integer messageID) {
    this.messageID = messageID;
    return this;
  }

  /**
   * Get messageID
   * @return messageID
   */
  @javax.annotation.Nonnull
  public Integer getMessageID() {
    return messageID;
  }

  public void setMessageID(@javax.annotation.Nonnull Integer messageID) {
    this.messageID = messageID;
  }


  public InterrogationStation1Msg1 slotOffset(@javax.annotation.Nonnull Integer slotOffset) {
    this.slotOffset = slotOffset;
    return this;
  }

  /**
   * Get slotOffset
   * @return slotOffset
   */
  @javax.annotation.Nonnull
  public Integer getSlotOffset() {
    return slotOffset;
  }

  public void setSlotOffset(@javax.annotation.Nonnull Integer slotOffset) {
    this.slotOffset = slotOffset;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InterrogationStation1Msg1 interrogationStation1Msg1 = (InterrogationStation1Msg1) o;
    return Objects.equals(this.valid, interrogationStation1Msg1.valid) &&
        Objects.equals(this.stationID, interrogationStation1Msg1.stationID) &&
        Objects.equals(this.messageID, interrogationStation1Msg1.messageID) &&
        Objects.equals(this.slotOffset, interrogationStation1Msg1.slotOffset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(valid, stationID, messageID, slotOffset);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InterrogationStation1Msg1 {\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("    stationID: ").append(toIndentedString(stationID)).append("\n");
    sb.append("    messageID: ").append(toIndentedString(messageID)).append("\n");
    sb.append("    slotOffset: ").append(toIndentedString(slotOffset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Valid");
    openapiFields.add("StationID");
    openapiFields.add("MessageID");
    openapiFields.add("SlotOffset");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("Valid");
    openapiRequiredFields.add("StationID");
    openapiRequiredFields.add("MessageID");
    openapiRequiredFields.add("SlotOffset");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to InterrogationStation1Msg1
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!InterrogationStation1Msg1.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InterrogationStation1Msg1 is not found in the empty JSON string", InterrogationStation1Msg1.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!InterrogationStation1Msg1.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `InterrogationStation1Msg1` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : InterrogationStation1Msg1.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InterrogationStation1Msg1.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InterrogationStation1Msg1' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InterrogationStation1Msg1> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InterrogationStation1Msg1.class));

       return (TypeAdapter<T>) new TypeAdapter<InterrogationStation1Msg1>() {
           @Override
           public void write(JsonWriter out, InterrogationStation1Msg1 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public InterrogationStation1Msg1 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of InterrogationStation1Msg1 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of InterrogationStation1Msg1
   * @throws IOException if the JSON string is invalid with respect to InterrogationStation1Msg1
   */
  public static InterrogationStation1Msg1 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InterrogationStation1Msg1.class);
  }

  /**
   * Convert an instance of InterrogationStation1Msg1 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

