/*
 * Ais-Stream WebsocketObjects
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * StandardClassBPositionReport
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-21T15:33:26.956655+01:00[Europe/Berlin]", comments = "Generator version: 7.11.0")
public class StandardClassBPositionReport {
  public static final String SERIALIZED_NAME_MESSAGE_I_D = "MessageID";
  @SerializedName(SERIALIZED_NAME_MESSAGE_I_D)
  @javax.annotation.Nonnull
  private Integer messageID;

  public static final String SERIALIZED_NAME_REPEAT_INDICATOR = "RepeatIndicator";
  @SerializedName(SERIALIZED_NAME_REPEAT_INDICATOR)
  @javax.annotation.Nonnull
  private Integer repeatIndicator;

  public static final String SERIALIZED_NAME_USER_I_D = "UserID";
  @SerializedName(SERIALIZED_NAME_USER_I_D)
  @javax.annotation.Nonnull
  private Integer userID;

  public static final String SERIALIZED_NAME_VALID = "Valid";
  @SerializedName(SERIALIZED_NAME_VALID)
  @javax.annotation.Nonnull
  private Boolean valid;

  public static final String SERIALIZED_NAME_SPARE1 = "Spare1";
  @SerializedName(SERIALIZED_NAME_SPARE1)
  @javax.annotation.Nonnull
  private Integer spare1;

  public static final String SERIALIZED_NAME_SOG = "Sog";
  @SerializedName(SERIALIZED_NAME_SOG)
  @javax.annotation.Nonnull
  private Double sog;

  public static final String SERIALIZED_NAME_POSITION_ACCURACY = "PositionAccuracy";
  @SerializedName(SERIALIZED_NAME_POSITION_ACCURACY)
  @javax.annotation.Nonnull
  private Boolean positionAccuracy;

  public static final String SERIALIZED_NAME_LONGITUDE = "Longitude";
  @SerializedName(SERIALIZED_NAME_LONGITUDE)
  @javax.annotation.Nonnull
  private Double longitude;

  public static final String SERIALIZED_NAME_LATITUDE = "Latitude";
  @SerializedName(SERIALIZED_NAME_LATITUDE)
  @javax.annotation.Nonnull
  private Double latitude;

  public static final String SERIALIZED_NAME_COG = "Cog";
  @SerializedName(SERIALIZED_NAME_COG)
  @javax.annotation.Nonnull
  private Double cog;

  public static final String SERIALIZED_NAME_TRUE_HEADING = "TrueHeading";
  @SerializedName(SERIALIZED_NAME_TRUE_HEADING)
  @javax.annotation.Nonnull
  private Integer trueHeading;

  public static final String SERIALIZED_NAME_TIMESTAMP = "Timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  @javax.annotation.Nonnull
  private Integer timestamp;

  public static final String SERIALIZED_NAME_SPARE2 = "Spare2";
  @SerializedName(SERIALIZED_NAME_SPARE2)
  @javax.annotation.Nonnull
  private Integer spare2;

  public static final String SERIALIZED_NAME_CLASS_B_UNIT = "ClassBUnit";
  @SerializedName(SERIALIZED_NAME_CLASS_B_UNIT)
  @javax.annotation.Nonnull
  private Boolean classBUnit;

  public static final String SERIALIZED_NAME_CLASS_B_DISPLAY = "ClassBDisplay";
  @SerializedName(SERIALIZED_NAME_CLASS_B_DISPLAY)
  @javax.annotation.Nonnull
  private Boolean classBDisplay;

  public static final String SERIALIZED_NAME_CLASS_B_DSC = "ClassBDsc";
  @SerializedName(SERIALIZED_NAME_CLASS_B_DSC)
  @javax.annotation.Nonnull
  private Boolean classBDsc;

  public static final String SERIALIZED_NAME_CLASS_B_BAND = "ClassBBand";
  @SerializedName(SERIALIZED_NAME_CLASS_B_BAND)
  @javax.annotation.Nonnull
  private Boolean classBBand;

  public static final String SERIALIZED_NAME_CLASS_B_MSG22 = "ClassBMsg22";
  @SerializedName(SERIALIZED_NAME_CLASS_B_MSG22)
  @javax.annotation.Nonnull
  private Boolean classBMsg22;

  public static final String SERIALIZED_NAME_ASSIGNED_MODE = "AssignedMode";
  @SerializedName(SERIALIZED_NAME_ASSIGNED_MODE)
  @javax.annotation.Nonnull
  private Boolean assignedMode;

  public static final String SERIALIZED_NAME_RAIM = "Raim";
  @SerializedName(SERIALIZED_NAME_RAIM)
  @javax.annotation.Nonnull
  private Boolean raim;

  public static final String SERIALIZED_NAME_COMMUNICATION_STATE_IS_ITDMA = "CommunicationStateIsItdma";
  @SerializedName(SERIALIZED_NAME_COMMUNICATION_STATE_IS_ITDMA)
  @javax.annotation.Nonnull
  private Boolean communicationStateIsItdma;

  public static final String SERIALIZED_NAME_COMMUNICATION_STATE = "CommunicationState";
  @SerializedName(SERIALIZED_NAME_COMMUNICATION_STATE)
  @javax.annotation.Nonnull
  private Integer communicationState;

  public StandardClassBPositionReport() {
  }

  public StandardClassBPositionReport messageID(@javax.annotation.Nonnull Integer messageID) {
    this.messageID = messageID;
    return this;
  }

  /**
   * Get messageID
   * @return messageID
   */
  @javax.annotation.Nonnull
  public Integer getMessageID() {
    return messageID;
  }

  public void setMessageID(@javax.annotation.Nonnull Integer messageID) {
    this.messageID = messageID;
  }


  public StandardClassBPositionReport repeatIndicator(@javax.annotation.Nonnull Integer repeatIndicator) {
    this.repeatIndicator = repeatIndicator;
    return this;
  }

  /**
   * Get repeatIndicator
   * @return repeatIndicator
   */
  @javax.annotation.Nonnull
  public Integer getRepeatIndicator() {
    return repeatIndicator;
  }

  public void setRepeatIndicator(@javax.annotation.Nonnull Integer repeatIndicator) {
    this.repeatIndicator = repeatIndicator;
  }


  public StandardClassBPositionReport userID(@javax.annotation.Nonnull Integer userID) {
    this.userID = userID;
    return this;
  }

  /**
   * Get userID
   * @return userID
   */
  @javax.annotation.Nonnull
  public Integer getUserID() {
    return userID;
  }

  public void setUserID(@javax.annotation.Nonnull Integer userID) {
    this.userID = userID;
  }


  public StandardClassBPositionReport valid(@javax.annotation.Nonnull Boolean valid) {
    this.valid = valid;
    return this;
  }

  /**
   * Get valid
   * @return valid
   */
  @javax.annotation.Nonnull
  public Boolean getValid() {
    return valid;
  }

  public void setValid(@javax.annotation.Nonnull Boolean valid) {
    this.valid = valid;
  }


  public StandardClassBPositionReport spare1(@javax.annotation.Nonnull Integer spare1) {
    this.spare1 = spare1;
    return this;
  }

  /**
   * Get spare1
   * @return spare1
   */
  @javax.annotation.Nonnull
  public Integer getSpare1() {
    return spare1;
  }

  public void setSpare1(@javax.annotation.Nonnull Integer spare1) {
    this.spare1 = spare1;
  }


  public StandardClassBPositionReport sog(@javax.annotation.Nonnull Double sog) {
    this.sog = sog;
    return this;
  }

  /**
   * Get sog
   * @return sog
   */
  @javax.annotation.Nonnull
  public Double getSog() {
    return sog;
  }

  public void setSog(@javax.annotation.Nonnull Double sog) {
    this.sog = sog;
  }


  public StandardClassBPositionReport positionAccuracy(@javax.annotation.Nonnull Boolean positionAccuracy) {
    this.positionAccuracy = positionAccuracy;
    return this;
  }

  /**
   * Get positionAccuracy
   * @return positionAccuracy
   */
  @javax.annotation.Nonnull
  public Boolean getPositionAccuracy() {
    return positionAccuracy;
  }

  public void setPositionAccuracy(@javax.annotation.Nonnull Boolean positionAccuracy) {
    this.positionAccuracy = positionAccuracy;
  }


  public StandardClassBPositionReport longitude(@javax.annotation.Nonnull Double longitude) {
    this.longitude = longitude;
    return this;
  }

  /**
   * Get longitude
   * @return longitude
   */
  @javax.annotation.Nonnull
  public Double getLongitude() {
    return longitude;
  }

  public void setLongitude(@javax.annotation.Nonnull Double longitude) {
    this.longitude = longitude;
  }


  public StandardClassBPositionReport latitude(@javax.annotation.Nonnull Double latitude) {
    this.latitude = latitude;
    return this;
  }

  /**
   * Get latitude
   * @return latitude
   */
  @javax.annotation.Nonnull
  public Double getLatitude() {
    return latitude;
  }

  public void setLatitude(@javax.annotation.Nonnull Double latitude) {
    this.latitude = latitude;
  }


  public StandardClassBPositionReport cog(@javax.annotation.Nonnull Double cog) {
    this.cog = cog;
    return this;
  }

  /**
   * Get cog
   * @return cog
   */
  @javax.annotation.Nonnull
  public Double getCog() {
    return cog;
  }

  public void setCog(@javax.annotation.Nonnull Double cog) {
    this.cog = cog;
  }


  public StandardClassBPositionReport trueHeading(@javax.annotation.Nonnull Integer trueHeading) {
    this.trueHeading = trueHeading;
    return this;
  }

  /**
   * Get trueHeading
   * @return trueHeading
   */
  @javax.annotation.Nonnull
  public Integer getTrueHeading() {
    return trueHeading;
  }

  public void setTrueHeading(@javax.annotation.Nonnull Integer trueHeading) {
    this.trueHeading = trueHeading;
  }


  public StandardClassBPositionReport timestamp(@javax.annotation.Nonnull Integer timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Get timestamp
   * @return timestamp
   */
  @javax.annotation.Nonnull
  public Integer getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(@javax.annotation.Nonnull Integer timestamp) {
    this.timestamp = timestamp;
  }


  public StandardClassBPositionReport spare2(@javax.annotation.Nonnull Integer spare2) {
    this.spare2 = spare2;
    return this;
  }

  /**
   * Get spare2
   * @return spare2
   */
  @javax.annotation.Nonnull
  public Integer getSpare2() {
    return spare2;
  }

  public void setSpare2(@javax.annotation.Nonnull Integer spare2) {
    this.spare2 = spare2;
  }


  public StandardClassBPositionReport classBUnit(@javax.annotation.Nonnull Boolean classBUnit) {
    this.classBUnit = classBUnit;
    return this;
  }

  /**
   * Get classBUnit
   * @return classBUnit
   */
  @javax.annotation.Nonnull
  public Boolean getClassBUnit() {
    return classBUnit;
  }

  public void setClassBUnit(@javax.annotation.Nonnull Boolean classBUnit) {
    this.classBUnit = classBUnit;
  }


  public StandardClassBPositionReport classBDisplay(@javax.annotation.Nonnull Boolean classBDisplay) {
    this.classBDisplay = classBDisplay;
    return this;
  }

  /**
   * Get classBDisplay
   * @return classBDisplay
   */
  @javax.annotation.Nonnull
  public Boolean getClassBDisplay() {
    return classBDisplay;
  }

  public void setClassBDisplay(@javax.annotation.Nonnull Boolean classBDisplay) {
    this.classBDisplay = classBDisplay;
  }


  public StandardClassBPositionReport classBDsc(@javax.annotation.Nonnull Boolean classBDsc) {
    this.classBDsc = classBDsc;
    return this;
  }

  /**
   * Get classBDsc
   * @return classBDsc
   */
  @javax.annotation.Nonnull
  public Boolean getClassBDsc() {
    return classBDsc;
  }

  public void setClassBDsc(@javax.annotation.Nonnull Boolean classBDsc) {
    this.classBDsc = classBDsc;
  }


  public StandardClassBPositionReport classBBand(@javax.annotation.Nonnull Boolean classBBand) {
    this.classBBand = classBBand;
    return this;
  }

  /**
   * Get classBBand
   * @return classBBand
   */
  @javax.annotation.Nonnull
  public Boolean getClassBBand() {
    return classBBand;
  }

  public void setClassBBand(@javax.annotation.Nonnull Boolean classBBand) {
    this.classBBand = classBBand;
  }


  public StandardClassBPositionReport classBMsg22(@javax.annotation.Nonnull Boolean classBMsg22) {
    this.classBMsg22 = classBMsg22;
    return this;
  }

  /**
   * Get classBMsg22
   * @return classBMsg22
   */
  @javax.annotation.Nonnull
  public Boolean getClassBMsg22() {
    return classBMsg22;
  }

  public void setClassBMsg22(@javax.annotation.Nonnull Boolean classBMsg22) {
    this.classBMsg22 = classBMsg22;
  }


  public StandardClassBPositionReport assignedMode(@javax.annotation.Nonnull Boolean assignedMode) {
    this.assignedMode = assignedMode;
    return this;
  }

  /**
   * Get assignedMode
   * @return assignedMode
   */
  @javax.annotation.Nonnull
  public Boolean getAssignedMode() {
    return assignedMode;
  }

  public void setAssignedMode(@javax.annotation.Nonnull Boolean assignedMode) {
    this.assignedMode = assignedMode;
  }


  public StandardClassBPositionReport raim(@javax.annotation.Nonnull Boolean raim) {
    this.raim = raim;
    return this;
  }

  /**
   * Get raim
   * @return raim
   */
  @javax.annotation.Nonnull
  public Boolean getRaim() {
    return raim;
  }

  public void setRaim(@javax.annotation.Nonnull Boolean raim) {
    this.raim = raim;
  }


  public StandardClassBPositionReport communicationStateIsItdma(@javax.annotation.Nonnull Boolean communicationStateIsItdma) {
    this.communicationStateIsItdma = communicationStateIsItdma;
    return this;
  }

  /**
   * Get communicationStateIsItdma
   * @return communicationStateIsItdma
   */
  @javax.annotation.Nonnull
  public Boolean getCommunicationStateIsItdma() {
    return communicationStateIsItdma;
  }

  public void setCommunicationStateIsItdma(@javax.annotation.Nonnull Boolean communicationStateIsItdma) {
    this.communicationStateIsItdma = communicationStateIsItdma;
  }


  public StandardClassBPositionReport communicationState(@javax.annotation.Nonnull Integer communicationState) {
    this.communicationState = communicationState;
    return this;
  }

  /**
   * Get communicationState
   * @return communicationState
   */
  @javax.annotation.Nonnull
  public Integer getCommunicationState() {
    return communicationState;
  }

  public void setCommunicationState(@javax.annotation.Nonnull Integer communicationState) {
    this.communicationState = communicationState;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StandardClassBPositionReport standardClassBPositionReport = (StandardClassBPositionReport) o;
    return Objects.equals(this.messageID, standardClassBPositionReport.messageID) &&
        Objects.equals(this.repeatIndicator, standardClassBPositionReport.repeatIndicator) &&
        Objects.equals(this.userID, standardClassBPositionReport.userID) &&
        Objects.equals(this.valid, standardClassBPositionReport.valid) &&
        Objects.equals(this.spare1, standardClassBPositionReport.spare1) &&
        Objects.equals(this.sog, standardClassBPositionReport.sog) &&
        Objects.equals(this.positionAccuracy, standardClassBPositionReport.positionAccuracy) &&
        Objects.equals(this.longitude, standardClassBPositionReport.longitude) &&
        Objects.equals(this.latitude, standardClassBPositionReport.latitude) &&
        Objects.equals(this.cog, standardClassBPositionReport.cog) &&
        Objects.equals(this.trueHeading, standardClassBPositionReport.trueHeading) &&
        Objects.equals(this.timestamp, standardClassBPositionReport.timestamp) &&
        Objects.equals(this.spare2, standardClassBPositionReport.spare2) &&
        Objects.equals(this.classBUnit, standardClassBPositionReport.classBUnit) &&
        Objects.equals(this.classBDisplay, standardClassBPositionReport.classBDisplay) &&
        Objects.equals(this.classBDsc, standardClassBPositionReport.classBDsc) &&
        Objects.equals(this.classBBand, standardClassBPositionReport.classBBand) &&
        Objects.equals(this.classBMsg22, standardClassBPositionReport.classBMsg22) &&
        Objects.equals(this.assignedMode, standardClassBPositionReport.assignedMode) &&
        Objects.equals(this.raim, standardClassBPositionReport.raim) &&
        Objects.equals(this.communicationStateIsItdma, standardClassBPositionReport.communicationStateIsItdma) &&
        Objects.equals(this.communicationState, standardClassBPositionReport.communicationState);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageID, repeatIndicator, userID, valid, spare1, sog, positionAccuracy, longitude, latitude, cog, trueHeading, timestamp, spare2, classBUnit, classBDisplay, classBDsc, classBBand, classBMsg22, assignedMode, raim, communicationStateIsItdma, communicationState);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StandardClassBPositionReport {\n");
    sb.append("    messageID: ").append(toIndentedString(messageID)).append("\n");
    sb.append("    repeatIndicator: ").append(toIndentedString(repeatIndicator)).append("\n");
    sb.append("    userID: ").append(toIndentedString(userID)).append("\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("    spare1: ").append(toIndentedString(spare1)).append("\n");
    sb.append("    sog: ").append(toIndentedString(sog)).append("\n");
    sb.append("    positionAccuracy: ").append(toIndentedString(positionAccuracy)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    cog: ").append(toIndentedString(cog)).append("\n");
    sb.append("    trueHeading: ").append(toIndentedString(trueHeading)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    spare2: ").append(toIndentedString(spare2)).append("\n");
    sb.append("    classBUnit: ").append(toIndentedString(classBUnit)).append("\n");
    sb.append("    classBDisplay: ").append(toIndentedString(classBDisplay)).append("\n");
    sb.append("    classBDsc: ").append(toIndentedString(classBDsc)).append("\n");
    sb.append("    classBBand: ").append(toIndentedString(classBBand)).append("\n");
    sb.append("    classBMsg22: ").append(toIndentedString(classBMsg22)).append("\n");
    sb.append("    assignedMode: ").append(toIndentedString(assignedMode)).append("\n");
    sb.append("    raim: ").append(toIndentedString(raim)).append("\n");
    sb.append("    communicationStateIsItdma: ").append(toIndentedString(communicationStateIsItdma)).append("\n");
    sb.append("    communicationState: ").append(toIndentedString(communicationState)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("MessageID");
    openapiFields.add("RepeatIndicator");
    openapiFields.add("UserID");
    openapiFields.add("Valid");
    openapiFields.add("Spare1");
    openapiFields.add("Sog");
    openapiFields.add("PositionAccuracy");
    openapiFields.add("Longitude");
    openapiFields.add("Latitude");
    openapiFields.add("Cog");
    openapiFields.add("TrueHeading");
    openapiFields.add("Timestamp");
    openapiFields.add("Spare2");
    openapiFields.add("ClassBUnit");
    openapiFields.add("ClassBDisplay");
    openapiFields.add("ClassBDsc");
    openapiFields.add("ClassBBand");
    openapiFields.add("ClassBMsg22");
    openapiFields.add("AssignedMode");
    openapiFields.add("Raim");
    openapiFields.add("CommunicationStateIsItdma");
    openapiFields.add("CommunicationState");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("MessageID");
    openapiRequiredFields.add("RepeatIndicator");
    openapiRequiredFields.add("UserID");
    openapiRequiredFields.add("Valid");
    openapiRequiredFields.add("Spare1");
    openapiRequiredFields.add("Sog");
    openapiRequiredFields.add("PositionAccuracy");
    openapiRequiredFields.add("Longitude");
    openapiRequiredFields.add("Latitude");
    openapiRequiredFields.add("Cog");
    openapiRequiredFields.add("TrueHeading");
    openapiRequiredFields.add("Timestamp");
    openapiRequiredFields.add("Spare2");
    openapiRequiredFields.add("ClassBUnit");
    openapiRequiredFields.add("ClassBDisplay");
    openapiRequiredFields.add("ClassBDsc");
    openapiRequiredFields.add("ClassBBand");
    openapiRequiredFields.add("ClassBMsg22");
    openapiRequiredFields.add("AssignedMode");
    openapiRequiredFields.add("Raim");
    openapiRequiredFields.add("CommunicationStateIsItdma");
    openapiRequiredFields.add("CommunicationState");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StandardClassBPositionReport
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StandardClassBPositionReport.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in StandardClassBPositionReport is not found in the empty JSON string", StandardClassBPositionReport.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!StandardClassBPositionReport.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `StandardClassBPositionReport` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : StandardClassBPositionReport.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StandardClassBPositionReport.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StandardClassBPositionReport' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StandardClassBPositionReport> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StandardClassBPositionReport.class));

       return (TypeAdapter<T>) new TypeAdapter<StandardClassBPositionReport>() {
           @Override
           public void write(JsonWriter out, StandardClassBPositionReport value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StandardClassBPositionReport read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StandardClassBPositionReport given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StandardClassBPositionReport
   * @throws IOException if the JSON string is invalid with respect to StandardClassBPositionReport
   */
  public static StandardClassBPositionReport fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StandardClassBPositionReport.class);
  }

  /**
   * Convert an instance of StandardClassBPositionReport to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

