stages:
  - build-and-test
  - dockerize-and-push
  - trigger_integrationtest_pipeline

variables:
  # Instruct Testcontainers to use the daemon of DinD, use port 2375 for non-tls connections.
  DOCKER_HOST: "tcp://docker:2375"
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: "overlay2"

services:
  - name: docker:27.3.1-dind
    alias: docker
    # explicitly disable tls to avoid docker startup interruption
    command: [ "--tls=false" ]

build-and-test:
  stage: build-and-test
  image: eclipse-temurin:23-jdk-noble
  tags:
    - dind
    - docker
  script:
    - ./gradlew build
  artifacts:
    when: always
    paths:
      - build/reports/
      - build/quarkus-app/ # save built application after

dockerize-and-push:
  stage: dockerize-and-push
  image: docker:27.3.1-cli
  tags:
    - dind
    - docker
  before_script:
    - apk add --no-cache bash # install bash
    - printf "Registry image is \"$CI_REGISTRY_IMAGE\"\n"
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin # log into registry
    - docker build -f src/main/docker/Dockerfile.jvm -t $CI_REGISTRY_IMAGE .
    - docker image push $CI_REGISTRY_IMAGE # push image to registry (like a remote repository for docker images)
  dependencies:
    - build-and-test

trigger_integrationtest_pipeline:
  stage: trigger_integrationtest_pipeline
  image: alpine/curl:8.9.1
  script:
    - 'curl -fail --request POST --form token=$TRIGGER_TOKEN --form ref=main "https://git.haw-hamburg.de/api/v4/projects/3554/trigger/pipeline"'
  dependencies:
    - dockerize-and-push
